name: docker-build-push-api

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Install Commitizen
        run: pip install -U Commitizen
      - 
        name: Set Version
        run: |
          echo "COMMITIZEN_VER=$(cz version -p)" >> $GITHUB_ENV
        id: commitizen-version
      - 
        name: Echo Current Version
        run: |
          echo "The current version is: ${{ env.COMMITIZEN_VER }}"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bourbon-buddy-api:latest,ghcr.io/${{ github.repository_owner }}/bourbon-buddy-api:${{ env.COMMITIZEN_VER }}
